# Site settings
baseurl      = "https://bodge.team"
languageCode = "en-us"
title        = "badge.team"
theme        = "bodgetheme"

# File locations
contentdir = "content"
datadir    = "data"
layoutdir  = "layouts"
publishdir = "public"

# Default pagination settings
paginate       = 10
paginatepath   = "p"

# Preferences robots.txt
enableRobotsTXT = true

enableEmoji = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  slug     = "slugs"
  project  = "projects"
  blog     = "blogs"
  team     = "teams"
  nickname = "nicknames"
