# Site settings
baseurl      = "https://bodge.team"
languageCode = "en-us"
title        = "badge.team"
theme        = "bodgetheme"

contentdir = "content"
datadir    = "data"
layoutdir  = "layouts"
publishdir = "public"

[taxonomies]
  tag      = "tags"
  category = "categories"
  project  = "projects"
  blog     = "blogs"
  team     = "teams"
  nickname = "nicknames"

[params]
  mainSections = ["blog","project"]
  defaultImage = "/images/mascot_600x600.png"
