# Site settings
baseurl      = "https://bodge.team"
languageCode = "en-us"
title        = "badge.team"
theme        = "bodgetheme"

# File locations
contentdir = "content"
datadir    = "data"
layoutdir  = "layouts"
publishdir = "public"

# Default pagination settings
paginate     = 10
paginatepath = "p"

# Preferences robots.txt
enableRobotsTXT = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  project  = "projects"
  blog     = "blogs"
  team     = "teams"
  nickname = "nicknames"

[params]
  mainSections = ["blog","project"]
  defaultImage = "/images/mascot_600x600.png"

  [params.blog]
    paginate = 5

  [params.project]
    paginate = 5

  [params.team]
    paginate = 12

  [params.gallery]
    maximage = 4
    paginate = 12

    [params.gallery.project]
      maximage = 4
      paginate = 12
