# Site settings
baseurl      = "https://bodge.team"
languageCode = "en-us"
title        = "badge.team"
theme        = "bodgetheme"

contentdir = "content"
datadir    = "data"
layoutdir  = "layouts"
publishdir = "public"

[taxonomies]
  tag      = "tags"
  category = "categories"
  activity = "activities"

[params]
  mainSections = ["blogs"]
