# Site settings
baseurl      = "https://bodge.team"
languageCode = "en-us"
title        = "Badge Team"
theme        = "bodgetheme"
copyright    = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

# File locations
contentdir = "content"
datadir    = "data"
layoutdir  = "layouts"
publishdir = "public"

# Default pagination settings
paginate       = 10
paginatepath   = "p"

# Preferences robots.txt
enableRobotsTXT = true

# Miscellaneous item (until we find a better place)
enableEmoji = true
rssLimit    = 25

[taxonomies]
  tag      = "tags"
  category = "categories"
  event    = "events"
  project  = "projects"
  blog     = "blogs"
  team     = "teams"
  nickname = "nicknames"

[outputs]
  home = [ "HTML", "RSS" ]
  section = [ "HTML", "RSS" ]

[minify]
  disableCSS   = false
  disableHTML  = false
  disableJS    = false
  disableJSON  = false
  disableSVG   = false
  disableXML   = false
  minifyOutput = false
  [minify.tdewolff]
    [minify.tdewolff.css]
      decimals = -1
      keepCSS2 = true
    [minify.tdewolff.html]
      keepConditionalComments = true
      keepDefaultAttrVals     = true
      keepDocumentTags        = true
      keepEndTags             = true
      keepWhitespace          = false
    [minify.tdewolff.js]
    [minify.tdewolff.json]
    [minify.tdewolff.svg]
      decimals = -1
    [minify.tdewolff.xml]
      keepWhitespace = false

[permalinks]
  project = "/:slug/"
  #blog    = "/:year/:month/:title/"
