# Hamburger menu items
#   Configure additional menu items in the 'Hamburger' menu.
#   The weight parameter defines the order that the links will appear in.

# [[main]]
#   identifier = "projects"
#   name       = "Projects"
#   title      = "Projects"
#   url        = "/project/"
#   parent     = ""
#   weight     = 10
#   pre        = ""
#   post       = ""
#
# [[main]]
#   identifier = ""
#   name       = "Bodgetheme"
#   title      = "Bodgetheme"
#   url        = "/project/bodgetheme2020/"
#   parent     = "projects"
#   weight     = 20
#   pre        = ""
#   post       = ""
#
# [[main]]
#   identifier = "ident03"
#   name       = "Name03"
#   title      = "Title03"
#   url        = "#url03"
#   parent     = ""
#   weight     = 30
#   pre        = ""
#   post       = ""
#
# [[main]]
#   identifier = "ident04"
#   name       = "Name04"
#   title      = "Title04"
#   url        = "#url04"
#   parent     = "ident03"
#   weight     = 30
#   pre        = ""
#   post       = ""

# Top navigation bar items
#   This allows you to add an additional button to the top navigation bar,
#   in a Hugo-menu-item manner.
#   NOTE: You are strongly encouraged to configure additional items in
#         the navbar structure in the Params-configuration, which allows
#         for a bit more flexibility and less html screw-ups.

[[navbar_top]]
  identifier = "projects"
  name       = "Projects"
  title      = "Projects"
  url        = "/project/"
  parent     = ""
  weight     = 10
  pre        = "<i class='fa fa-cogs bt-hover-opacity'></i> "
  post       = ""

[[navbar_top]]
  identifier = ""
  name       = "Bodgetheme"
  title      = "Bodgetheme"
  url        = "/bodgetheme2020/"
  parent     = "projects"
  weight     = 10
  pre        = "<i class='fa fa-hackaday bt-hover-opacity'></i> "
  post       = ""
#
# [[navbar_top]]
#   identifier = "team"
#   name       = "Team"
#   title      = "Team"
#   url        = "/team/"
#   parent     = ""
#   weight     = 20
#   pre        = "<i class='fa fa-users bt-hover-opacity'></i> "
#   post       = ""
#
# [[navbar_top]]
#   identifier = ""
#   name       = "Elborro"
#   title      = "Elborro"
#   url        = "/team/elborro/"
#   parent     = "team"
#   weight     = 20
#   pre        = "<i class='fa fa-rebel fa-spin bt-hover-opacity'></i> "
#   post       = ""

  # Bottom navigation bar items
  #   This allows you to add an additional button to the bottom navigation bar,
  #   in a Hugo-menu-item manner.
  #   NOTE: You are strongly encouraged to configure additional items in
  #         the navbar structure in the Params-configuration, which allows
  #         for a bit more flexibility and less html screw-ups.

# [[navbar_bottom]]
#   identifier = "ident01"
#   name       = "Name01"
#   title      = "Title01"
#   url        = "/"
#   parent     = ""
#   weight     = 10
#   pre        = "<i class='fa fa-hackaday bt-hover-opacity'></i>"
#   post       = ""
